### ISSUE TITLE
New release for non-vulnerable hoek version

### ISSUE THREAD

**Issue by tjorim** [travishorn/csval#36]
hoek subject to prototype pollution via the clone function.
Dependabot cannot update @hapi/hoek to a non-vulnerable version
The latest possible version that can be installed is 6.2.4 because of the following conflicting dependencies:

csval@1.1.1 requires @hapi/hoek@6.x.x via @hapi/joi@14.5.0
csval@1.1.1 requires @hapi/hoek@^6.0.0 via enjoi@6.0.2
csval@1.1.1 requires @hapi/hoek@^8.3.0 via a transitive dependency on @hapi/topo@3.1.6
No patched version available for @hapi/hoek
The earliest fixed version is 9.0.4.

hoek versions prior to 8.5.1, and 9.x prior to 9.0.3 are vulnerable to prototype pollution in the clone function. If an object with the proto key is passed to clone() the key is converted to a prototype. This issue has been patched in version 9.0.3, and backported to 8.5.1.

**Comment by travishorn** [comment]
I solved this by rewriting the validation function to use Ajv instead of enjoi and joi . There is no more dependency on @hapi/hoek.

Although the API is virtually the same, this is a major release because:

- the programmatic API now uses ES modules (`import { validate } from "csval";`)
- some objects/properties are interpreted by Ajv differently than Joi
- the error messages are different

commit 633400e39b25bb934a0f07c4d43ec8ac59c6a222
